name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Running Open Source Security by Snyk (SCA)
      run: |
          curl -Lo ./snyk "https://github.com/snyk/snyk/releases/download/v1.210.0/snyk-linux" 
          chmod -R +x ./snyk 
          ./snyk auth ${{ secrets.SNYK_AUTH_TOKEN }} 
          ./snyk monitor
          
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}     
        
    - name: Running Horusec Security (SAST)
      run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p .

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gooftest

      #Targeting dvwa.co.uk
#    - name: ZAP Scan (DAST)
#      uses: zaproxy/action-full-scan@v0.3.0
#      with:
#        target: 'https://dvwa.co.uk/'
#testing
